// Generated by https://quicktype.io

export interface APIRespt {
    info: Info;
    results: Person[];
}

export interface Info {
    count: number;
    pages: number;
    next: string;
    prev: null;
}

export interface Person {
    id: number;
    name: string;
    status: string;
    species: string;
    type: string;
    gender: string;
    origin: Location;
    location: Location;
    image: string;
    episode: string[];
    url: string;
    created: string;
}

export interface Location {
    name: string;
    url: string;
}

